// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Met")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Domain.Aggregates.ExerciseProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Met")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("ExerciseProposals");
                });

            modelBuilder.Entity("Domain.Aggregates.PersonalHealthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PersonalHealthAccounts");
                });

            modelBuilder.Entity("Domain.Aggregates.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Domain.Aggregates.WeightHistoryPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateOnly(2026, 5, 16));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WeightHistoryPoint");
                });

            modelBuilder.Entity("Domain.Aggregates.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Domain.Aggregates.Exercise", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Media", "PerformanceVideo", b1 =>
                        {
                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExerciseId");

                            b1.ToTable("Exercises");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Media", "Photo", b1 =>
                        {
                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Bucket");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExerciseId");

                            b1.ToTable("Exercises");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseId");
                        });

                    b.Navigation("PerformanceVideo")
                        .IsRequired();

                    b.Navigation("Photo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ExerciseProposal", b =>
                {
                    b.HasOne("Domain.Aggregates.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Media", "EmgVideo", b1 =>
                        {
                            b1.Property<Guid>("ExerciseProposalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExerciseProposalId");

                            b1.ToTable("ExerciseProposals");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseProposalId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Media", "PerformanceVideo", b1 =>
                        {
                            b1.Property<Guid>("ExerciseProposalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExerciseProposalId");

                            b1.ToTable("ExerciseProposals");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseProposalId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Media", "Photo", b1 =>
                        {
                            b1.Property<Guid>("ExerciseProposalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Bucket");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ExerciseProposalId");

                            b1.ToTable("ExerciseProposals");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseProposalId");
                        });

                    b.Navigation("EmgVideo")
                        .IsRequired();

                    b.Navigation("PerformanceVideo")
                        .IsRequired();

                    b.Navigation("Photo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.PersonalHealthAccount", b =>
                {
                    b.HasOne("Domain.Aggregates.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Domain.Aggregates.PersonalHealthAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("PersonalHealthAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("date_of_birth");

                            b1.Property<int>("Sex")
                                .HasColumnType("integer")
                                .HasColumnName("sex");

                            b1.HasKey("PersonalHealthAccountId");

                            b1.ToTable("PersonalHealthAccounts");

                            b1.WithOwner()
                                .HasForeignKey("PersonalHealthAccountId");

                            b1.OwnsOne("Domain.ValueObjects.Height", "Height", b2 =>
                                {
                                    b2.Property<Guid>("UserProfilePersonalHealthAccountId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Centimeters")
                                        .HasColumnType("integer")
                                        .HasColumnName("height");

                                    b2.HasKey("UserProfilePersonalHealthAccountId");

                                    b2.ToTable("PersonalHealthAccounts");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfilePersonalHealthAccountId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Weight", "Weight", b2 =>
                                {
                                    b2.Property<Guid>("UserProfilePersonalHealthAccountId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Kilograms")
                                        .HasColumnType("double precision")
                                        .HasColumnName("weight");

                                    b2.HasKey("UserProfilePersonalHealthAccountId");

                                    b2.ToTable("PersonalHealthAccounts");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfilePersonalHealthAccountId");
                                });

                            b1.Navigation("Height")
                                .IsRequired();

                            b1.Navigation("Weight")
                                .IsRequired();
                        });

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.WeightHistoryPoint", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Weight", "Weight", b1 =>
                        {
                            b1.Property<Guid>("WeightHistoryPointId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Kilograms")
                                .HasColumnType("double precision")
                                .HasColumnName("weight");

                            b1.HasKey("WeightHistoryPointId");

                            b1.ToTable("WeightHistoryPoint");

                            b1.WithOwner()
                                .HasForeignKey("WeightHistoryPointId");
                        });

                    b.Navigation("Weight")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.Workout", b =>
                {
                    b.OwnsMany("Domain.Entities.WorkoutExercise", "Exercises", b1 =>
                        {
                            b1.Property<Guid>("workout_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<double>("TotalCalories")
                                .HasColumnType("double precision");

                            b1.HasKey("workout_id", "Id");

                            b1.ToTable("workout_exercises", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("workout_id");

                            b1.OwnsOne("Domain.ValueObjects.ExerciseVolume", "Volume", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutExerciseworkout_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutExerciseId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Repetitions")
                                        .HasColumnType("integer")
                                        .HasColumnName("repetitions");

                                    b2.HasKey("WorkoutExerciseworkout_id", "WorkoutExerciseId");

                                    b2.ToTable("workout_exercises");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutExerciseworkout_id", "WorkoutExerciseId");

                                    b2.OwnsOne("Domain.ValueObjects.Weight", "Weight", b3 =>
                                        {
                                            b3.Property<Guid>("ExerciseVolumeWorkoutExerciseworkout_id")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ExerciseVolumeWorkoutExerciseId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Kilograms")
                                                .HasColumnType("double precision")
                                                .HasColumnName("weight_kg");

                                            b3.HasKey("ExerciseVolumeWorkoutExerciseworkout_id", "ExerciseVolumeWorkoutExerciseId");

                                            b3.ToTable("workout_exercises");

                                            b3.WithOwner()
                                                .HasForeignKey("ExerciseVolumeWorkoutExerciseworkout_id", "ExerciseVolumeWorkoutExerciseId");
                                        });

                                    b2.Navigation("Weight")
                                        .IsRequired();
                                });

                            b1.Navigation("Volume")
                                .IsRequired();
                        });

                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
