version: '3.8'

services:
  # Хранилище для видео и фото упражнений
  minio:
    image: minio/minio:latest
    container_name: fit-tracker-minio
    ports:
      - "9000:9000"    # API порт (для бэкенда)
      - "9001:9001"    # Консоль (для тебя, зайти в браузере)
    environment:
      MINIO_ROOT_USER: dev_user
      MINIO_ROOT_PASSWORD: dev_password_123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  # Кэш для черного списка токенов и ускорения работы
  redis:
    image: redis:7-alpine
    container_name: fit-tracker-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  minio_data: